### ISSUE TITLE
Specify execution order of plugins

### ISSUE THREAD

**Issue by hwuerz** [steep-wms/steep#12]
I can define plugins to adjust the execution behavior. It is possible to define multiple plugins of the same type. For example I can define two processChainAdapter plugins A and B. 
Currently their execution order is given by the definition order in the corresponding yaml file. This is an implicit definition and might change at any time in the future.

It would be nice to have an `order` attribute for each plugins. Plugins with a larger `order` are executed after plugins with a lower `order` independently of their definition order in the yaml file. 

Example:
```
- name: myPluginA
  type: processChainAdapter
  order: 2
  scriptFile: myPluginA.kt
- name: myPluginB
  type: processChainAdapter
  order: 1
  scriptFile: myPluginB.kt
```

In this case the plugin B should be executed before plugin A.

**Comment by michel-kraemer** [comment]
I think specifying dependencies is even better than the proposed `order` property because the order of plugins with the same value would still be undefined:

```
- name: myPluginA
  type: processChainAdapter
  order: 1
  scriptFile: myPluginA.kt
- name: myPluginB
  type: processChainAdapter
  order: 1
  scriptFile: myPluginB.kt
```

I propose something like this:

```
- name: myPluginA
  type: processChainAdapter
  dependencies:
    - myPluginB
  scriptFile: myPluginA.kt
- name: myPluginB
  type: processChainAdapter
  scriptFile: myPluginB.kt
```
