### ISSUE TITLE
Support for macros in workflows

### ISSUE THREAD

**Issue by hwuerz** [steep-wms/steep#980]
In daily use, there is often a sequence of services that is included in each of my workflows. For example, this can be copying data into my environment, or pre-processing before the actual calculation starts. However, at the moment I have to write these services every time into my workflow. 

It would be nice if I could outsource these steps to a macro. Similar to the `service.yaml` there would then be a `macro.yaml` containing predefined sequences of services (i.e. more or less small workflows). They also have inputs and outputs so that I can continue working with the results in my actual workflow.

For example, a `macro.yaml` could look like this:
```yaml
id: preparation
name: Preparation of data
inputs:
  - id: "source"
    var: "source"
outputs:
  - id: "destination"
    var: "destination"
actions:
  - type: execute
    service: download
    inputs:
      - id: "source"
        value: "source"
    outputs:
      - id: "output"
        var: downloadedData
  - type: execute
    service: preprocess
    inputs:
      - id: "input"
        value: "downloadedData"
    outputs:
      - id: "output"
        var: destination
```

This bundles the two services download and preprocess and makes them available as a macro preparation. 
In my workflow I could then use it like this:
```yaml
api: 4.6.0
actions:
  - type: macro
    macro: preparation
    inputs:
      - id: source
        value: http://example.com/my-data
    outputs:
      - id: destination
        var: preparedData
  - type: execute
    service: calculation
    inputs:
      - id: input
        var: preparedData
    outputs:
      - id: output
        var: outputDirectory
```

Can something like this be added to Steep?
